inherit_from:
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - gemfiles/*.gemfile

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Metrics/MethodLength:
  Exclude:
    - db/migrate/1_gutentag_tables.rb

Style/MultilineIfModifier:
  Exclude:
    - Appraisals
    - spec/acceptance/tag_names_spec.rb

Style/MultilineTernaryOperator:
  Exclude:
    - db/migrate/*.rb

Style/SafeNavigation:
  Enabled: false
