language: ruby
dist: xenial
script: bundle exec appraisal rake
rvm:
  - jruby-9.2.5.0
before_install:
  - gem update --system
  - gem install bundler --version 1.17.3
install:
  - bundle _1.17.3_ install --jobs=3 --retry=3
before_script:
  - bundle exec appraisal install
env:
  - DATABASE=postgres
  - DATABASE=mysql
  - DATABASE=sqlite
services:
- mysql
- postgresql
