language: ruby
dist: xenial
script: bundle exec appraisal rake
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby-9.2.5.0
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
before_script:
  - bundle exec appraisal install
env:
  - DATABASE=postgres
  - DATABASE=mysql
  - DATABASE=sqlite
services:
- mysql
- postgresql
