language: ruby
script: bundle exec appraisal rake
rvm:
  - jruby-9.2.5.0
before_install:
  - gem update --system
  - gem uninstall bundler --all --ignore-dependencies --executables
  - gem install bundler --version "~> 1.17"
before_script:
  - bundle exec appraisal install
env:
  - DATABASE=postgres
  - DATABASE=mysql
  - DATABASE=sqlite
